[package]
name = "push-chess"
version = "0.1.0"
edition = "2024"
default-run = "play"

[dependencies]
arrayvec = "0.7"
smallvec = { version = "1.15", features = ["const_generics"] }
rusqlite = { version = "0.31", features = ["bundled"] }
crossterm = "0.28"
ratatui = "0.29"

[profile.release]
opt-level = 2
lto = "thin"

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"
invalid_value = "deny"

[[bin]]
name = "showdown"
path = "src/bin/showdown.rs"

[[bin]]
name = "replay"
path = "src/bin/replay.rs"

[[bin]]
name = "play"
path = "src/bin/play.rs"

[[bin]]
name = "dump"
path = "src/bin/dump.rs"
