"""Fetch pinned arXiv sources without compiling or executing their contents.

Stdlib only. Run from any directory. Existing completed entries are preserved.
--verify checks local hashes without network access. Metadata and status files
are generated by this script; paper texts retain their upstream licenses.
"""
from __future__ import annotations

import argparse
from datetime import datetime, timezone
import gzip
import hashlib
import io
import json
from pathlib import Path, PurePosixPath
import re
import tarfile
import time
import urllib.parse
import urllib.request
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parent
MAX_DOWNLOAD = 64 * 1024 * 1024
MAX_EXPANDED = 256 * 1024 * 1024
MAX_TEXT = 24 * 1024 * 1024
TEXT_SUFFIXES = {".tex", ".ltx", ".bib", ".bbl", ".sty", ".cls", ".bst", ".def", ".clo", ".cfg", ".txt", ".md"}
ATOM = {"a": "http://www.w3.org/2005/Atom"}
last_request = 0.0


def digest(data):
    return hashlib.sha256(data).hexdigest()


def check_pinned(identifier, archive_hash):
    manifest = ROOT / "manifest.json"
    if manifest.exists():
        entries = json.loads(manifest.read_text())["papers"]
        expected = next((p for p in entries if p["id"] == identifier), None)
        if expected and expected["archive"]["sha256"] != archive_hash:
            raise ValueError(f"pinned source archive changed; review required: {identifier}")


def fetch(url, limit=MAX_DOWNLOAD):
    global last_request
    time.sleep(max(0, 3.1 - (time.monotonic() - last_request)))
    last_request = time.monotonic()
    request = urllib.request.Request(url, headers={"User-Agent": "PushChessResearchLibrary/1.0 (private scholarly source archive)"})
    with urllib.request.urlopen(request, timeout=25) as response:
        chunks, size = [], 0
        while chunk := response.read(64 * 1024):
            size += len(chunk)
            if size > limit or time.monotonic() - last_request > 90:
                raise ValueError("download size/time limit exceeded")
            chunks.append(chunk)
        return b"".join(chunks), response.headers.get_content_type(), response.geturl()


def safe_name(name):
    path = PurePosixPath(name)
    if path.is_absolute() or ".." in path.parts or "\\" in name or ":" in name or not path.parts:
        raise ValueError(f"unsafe archive path: {name!r}")
    return path


def wanted(path):
    return path.suffix.lower() in TEXT_SUFFIXES or path.name.lower().startswith(("license", "licence", "copying", "readme"))


def unpack(data):
    """Return bounded regular text members; never follow links or extractall."""
    try:
        archive = tarfile.open(fileobj=io.BytesIO(data), mode="r:*")
    except tarfile.ReadError:
        if data.startswith(b"\x1f\x8b"):
            with gzip.GzipFile(fileobj=io.BytesIO(data)) as stream:
                raw = stream.read(MAX_TEXT + 1)
            kind = "source.tex.gz"
        else:
            raw, kind = data, "source.tex"
        if len(raw) > MAX_TEXT or b"\\document" not in raw or raw.startswith(b"%PDF") or b"\x00" in raw:
            raise ValueError("not an identifiable LaTeX source submission")
        return kind, [("main.tex", raw)], []
    kept, skipped, seen = [], [], set()
    expanded = text_size = 0
    with archive:
        for index, member in enumerate(archive):
            if index >= 8192:
                raise ValueError("too many archive members")
            path = safe_name(member.name)
            if member.isdir():
                continue
            if not member.isfile():
                raise ValueError(f"non-regular archive member: {member.name}")
            expanded += member.size
            if expanded > MAX_EXPANDED:
                raise ValueError("expanded archive size limit exceeded")
            if not wanted(path):
                skipped.append(str(path))
                continue
            text_size += member.size
            if text_size > MAX_TEXT or len(kept) >= 1024 or str(path) in seen:
                raise ValueError("text size/count limit or duplicate member")
            raw = archive.extractfile(member).read(member.size + 1)
            if len(raw) != member.size or b"\x00" in raw:
                raise ValueError(f"invalid text member: {member.name}")
            seen.add(str(path))
            kept.append((str(path), raw))
    if not any(name.lower().endswith((".tex", ".ltx")) for name, _ in kept):
        raise ValueError("submission contains no LaTeX source")
    return "source.tar.gz" if data.startswith(b"\x1f\x8b") else "source.tar", kept, skipped


def write_new(path, data):
    path.parent.mkdir(parents=True, exist_ok=True)
    # Neither replace existing files nor follow an existing final symlink.
    if any(p.is_symlink() for p in (path, *path.parents)):
        raise ValueError(f"symlink in destination: {path}")
    with path.open("xb") as out:
        out.write(data)


def save_json(path, value):
    write_new(path, (json.dumps(value, indent=2, ensure_ascii=False) + "\n").encode())


def verify(directory):
    meta = json.loads((directory / "metadata.json").read_text())
    check_pinned(meta["id"], meta["archive"]["sha256"])
    items = [meta["archive"], *meta["extracted"],
             {"path": "arxiv-entry.xml", "sha256": meta["metadata_xml_sha256"]}]
    for item in items:
        path = directory.joinpath(*safe_name(item["path"]).parts)
        if path.is_symlink() or digest(path.read_bytes()) != item["sha256"]:
            raise ValueError(f"hash mismatch: {path}")
    return len(meta["extracted"])


def download(paper):
    identifier = paper["id"]
    directory = ROOT / "arxiv" / f"{identifier}-{paper['slug']}"
    if (directory / "metadata.json").exists():
        return {"id": identifier, "status": "verified-existing", "text_files": verify(directory)}
    if directory.exists():
        raise ValueError(f"incomplete directory; inspect manually, not overwritten: {directory}")
    url = "https://export.arxiv.org/api/query?" + urllib.parse.urlencode({"id_list": identifier})
    xml, _, _ = fetch(url, 1024 * 1024)
    entries = ET.fromstring(xml).findall("a:entry", ATOM)
    entry = next((e for e in entries if e.findtext("a:id", "", ATOM).rsplit("/", 1)[-1] == identifier), None)
    if entry is None:
        raise ValueError("arXiv metadata did not return requested version")
    source_url = f"https://arxiv.org/src/{identifier}"
    data, mime, final_url = fetch(source_url)
    check_pinned(identifier, digest(data))
    archive_name, members, skipped = unpack(data)
    write_new(directory / archive_name, data)
    write_new(directory / "arxiv-entry.xml", xml)
    extracted = []
    for name, raw in members:
        relative = "tex/" + name
        write_new(directory / relative, raw)
        extracted.append({"path": relative, "bytes": len(raw), "sha256": digest(raw)})
    title = " ".join(entry.findtext("a:title", "", ATOM).split())
    metadata = {
        **paper, "title": title,
        "authors": [a.findtext("a:name", "", ATOM) for a in entry.findall("a:author", ATOM)],
        "abstract": " ".join(entry.findtext("a:summary", "", ATOM).split()),
        "published": entry.findtext("a:published", "", ATOM),
        "updated": entry.findtext("a:updated", "", ATOM),
        "fetched_utc": datetime.now(timezone.utc).isoformat(),
        "abstract_url": f"https://arxiv.org/abs/{identifier}",
        "source_url": source_url, "resolved_source_url": final_url, "content_type": mime,
        "license": "Upstream rights retained. Consult archive notices and arXiv entry; no license inferred from public availability.",
        "archive": {"path": archive_name, "bytes": len(data), "sha256": digest(data)},
        "metadata_xml_sha256": digest(xml), "extracted": extracted,
        "unextracted_assets_in_archive": skipped,
        "safety": "Regular text files only. No TeX compilation or upstream code execution.",
    }
    save_json(directory / "metadata.json", metadata)
    return {"id": identifier, "title": title, "status": "downloaded", "text_files": len(members), "archive_bytes": len(data)}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--verify", action="store_true")
    parser.add_argument("--only", help="one exact pinned arXiv ID")
    args = parser.parse_args()
    papers = json.loads((ROOT / "papers.json").read_text())
    results = []
    for paper in papers:
        if args.only and paper["id"] != args.only:
            continue
        if not re.fullmatch(r"\d{4}\.\d{4,5}v\d+", paper["id"]) or not re.fullmatch(r"[a-z0-9-]+", paper["slug"]):
            raise ValueError("invalid catalog entry")
        try:
            if args.verify:
                count = verify(ROOT / "arxiv" / f"{paper['id']}-{paper['slug']}")
                result = {"id": paper["id"], "status": "verified", "text_files": count}
            else:
                result = download(paper)
        except Exception as error:
            result = {"id": paper["id"], "status": "unavailable-or-error", "error": str(error)}
        results.append(result)
        print(json.dumps(result), flush=True)
    if not results:
        parser.error("no matching catalog entries")
    if any(r["status"] == "unavailable-or-error" for r in results):
        raise SystemExit(1)


if __name__ == "__main__":
    main()
